### ISSUE TITLE
Add One More Hint

### ISSUE THREAD

**Issue by dung-dao-hoangg** [tannd-ds/vi-wiki-table-qa#3]
The tool is quite full of features. However, there are some missing things in your tool that make me feel inconvenient. So I am writing to inform you that your tool must be added a hint named "Tại Sao".

**Comment by tannd-ds** [comment]
# Thank you for your contribution and we've fixed the issue!

Dear @DuzDao,

I hope this message finds you well. First and foremost, I want to express my heartfelt gratitude for taking the time to provide us with your valuable feedback. Your input is incredibly important to us, as it helps us identify areas for improvement and make our tool even better.

I'm pleased to inform you that we have taken your suggestion to heart, and we have already implemented the feature you mentioned. I'm delighted to announce that the "Tại Sao" hint is now available in our tool. This new addition will certainly enhance the user experience and make it more convenient for you to use our tool.

We genuinely appreciate your dedication to helping us enhance our product, and we cannot thank you enough for contributing to its improvement. It's users like you who motivate us to constantly strive for excellence and create a tool that meets everyone's needs.

If you encounter any more suggestions or issues in the future, please do not hesitate to reach out to us. We are always here to listen to our users and make their experience with our tool as smooth and enjoyable as possible.

Once again, thank you for your valuable contribution, and we hope you continue to enjoy using our tool with the new "Tại Sao" hint!

*Tannd-ds*
